### ISSUE TITLE
szero Dependency

### ISSUE THREAD

**Issue by pandapaul** [bucharest-gold/keycloak-admin-client#26]
Might be good to include `szero` as a peer or dev dependency in the package.json and/or mention it in the readme.  I'm honestly not sure which one would be more correct, but since szero's documentation appears to suggest global install I guess peer would make more sense.

**Comment by helio-frota** [comment]
@pandapaul good!
https://github.com/bucharest-gold/keycloak-admin-client/blob/master/.travis.yml#L10
makes sense to add as `devDependency`, can you send a PR for this ? thanks!

**Comment by helio-frota** [comment]
I got it.

just random things...:

1. currently szero is used on CI -> only
2. the Makefile has the dependencyCheck entry, and until now we have no problem because, we are building and working with szero, so probably we will not see the error when running `make test`.
3. Adding this as devDependency will create kind of "redundant" install on travis

So the better way for contributions is to have as devDependency and remove the global install from travis. At least is better than "force" people to install szero globaly.

makes sense ?

**Comment by helio-frota** [comment]
@pandapaul thanks for pointing this.
Also I've updated another project, using this approach
https://github.com/bucharest-gold/drools-kie-client/commit/6068842441b7db8513cb79012879b2a90e5322bd

**Comment by pandapaul** [comment]
@helio-frota Yeah actually my personal preference with things like this is usually to just add them to devDependencies so that `npm install` just takes care of it.  Then it would definitely be redundant with the the global install in the travis yml, which could be removed.  Any mention of `szero` in the package.json or readme will help to explain the build steps though, I think.

**Comment by pandapaul** [comment]
Resolved by https://github.com/bucharest-gold/keycloak-admin-client/commit/9a49c770bec156fe25c9076b1cbd24e5ac571794
